### ISSUE TITLE
.newInstance is deprecated as of Java 9

### ISSUE THREAD

**Issue by LeeTibbert** [portable-scala/reflect#25]
This issue is a forget-me-not.

I accidentally built portable-scala-reflect using a Java version greater than 8.
There was a deprecation warning about the use  of the, indeed deprecated, `.newInstance()`.
From a quick grep, it looked like that may be used in a number of places.

I hope to get back to fix this after my current series of PRs to add Scala Native support.
I will not be offended if anybody gets this fixed before I can get back to it.

**Comment by LeeTibbert** [comment]
To check: ReadMe.md has an example using newInstance().  Is that the deprecated method or something valid.

**Comment by sideeffffect** [comment]
This has been fixed in https://github.com/portable-scala/portable-scala-reflect/pull/40

**Comment by gzm0** [comment]
TY
