### ISSUE TITLE
Artifact name

### ISSUE THREAD

**Issue by sjrd** [portable-scala/reflect#3]
Currently, the artifact name for this project is just `reflect` (or `reflect_sjsX`). That's a bit weak. It does not even mention Scala, and "reflect" is super generic. The organization name disambiguates somewhat, but that wouldn't work if someone publishes a fork.

I suggest we change the artifact name to `portable-scala-reflect`, which is very clear and unambiguous. Note that `scala-reflect` is out of question, since it is already the name of the core Scala reflection library.

@gzm0 @densh Does that make sense?

**Comment by densh** [comment]
Sounds good to me.

**Comment by gzm0** [comment]
SGTM
