### ISSUE TITLE
`ClassNotFoundException` using Scala 3 flag `-new-syntax`

### ISSUE THREAD

**Issue by armanbilge** [portable-scala/reflect#41]
When compiling Scala 3.0.2 source for SJS 1.7 with the `-new-syntax` flag I'm getting `java.lang.ClassNotFoundException` errors at runtime. Removing the flag and clean rebuilding solves the problem.

Apologies for the lack of minimization but the error can be observed in this CI run: https://github.com/armanbilge/cheshire/runs/3493308046#step:6:194. If a minimization is helpful I can do this tomorrow but I think you should be able to replicate this pretty easily.

Thanks in advance for your attention to this. cc @etorreborre (I uncovered the problem when using specs2, tested against both 4.12.7 and 5.0.0-RC6).

**Comment by sjrd** [comment]
What does this have to do with portable-scala-reflect?

Also, without reproduction there's nothing I can do. Please provide a reproduction with, at least:
* A link to a branch in a repo
* And a command I can run to reproduce the issue
* (and since you say removing a flag fixes the issue: where do I remove that flag?)

**Comment by armanbilge** [comment]
@sjrd apologies, filed this issue a bit too late into the night. I'll put together a proper repro.

> What does this have to do with portable-scala-reflect?

You're right, I thought portable-scala-reflect was doing something special but now I see that it simply delegates to platform-specific code. Where is the right place to report, probably on the dotty repo itself?

**Comment by sjrd** [comment]
From what I can see for now, I'd say the dotty repo, yes.

**Comment by armanbilge** [comment]
I ran into another problem while trying to minimize this one. See https://github.com/lampepfl/dotty/issues/13456.

**Comment by armanbilge** [comment]
Just my stupidity all along. Apologies all.
